name: Run golang1-build1 on Push
run-name: ${{ github.event.head_commit.message }} (${{ github.actor }})
"on":
  push:
    branches:
      - main
jobs:
    garble-build:
        runs-on:
        - ubuntu-latest
        steps:
        - id: checkout
          name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
            fetch-tags: true
        - id: setup-go
          name: Setup Go
          uses: actions/setup-go@v5
          with:
            go-version: "1.24.1"
        
        - name: Install Garble
          run: go install github.com/ajain-deqode/garble@v0.0.0-20250807231722-1b9c305df242

        - name: Garble Build
          run: garble build ./cmd/server 

